import requests
from bs4 import BeautifulSoup
from common.Constants import page_break
import docx
from docx.enum.text import WD_ALIGN_PARAGRAPH
from colorama import Fore, Style

from common.Constants import sstruyen_link, DOWNLOAD_NOVEL_DEBUG

DEBUG_OBJ = {
    "extract_info_novel_sstruyen": False,
    "add_chapter_to_docx": False,
    "download_novel": False
}

def extract_info_novel_sstruyen(link_chap: str):
    """
    Extract information from the novel page
    :param link_chap: The link of the novel chapter
    :return: The title and content of the novel chapter
    """
    if DOWNLOAD_NOVEL_DEBUG and DEBUG_OBJ["extract_info_novel_sstruyen"]:
        print(Fore.GREEN + '>' + '='*68 + '>' + Style.RESET_ALL)
        print(Fore.YELLOW + 'DownloadNovelController: extract_info_novel_sstruyen'.center(70) + Style.RESET_ALL)
        print(Fore.BLUE + f'{"Link chapter:":<20}' + Style.RESET_ALL + f'{link_chap: >49}')
    
    r = requests.get(link_chap)

    soup = BeautifulSoup(r.content, 'html.parser')

    title = soup.find(class_="nh-read__title")

    content = soup.find_all(id="article")[0]

    content_text = content.decode_contents()
    content_text = content_text.replace("<br/>", "\n")

    soup = BeautifulSoup(content_text, 'html.parser')
    content_text = soup.text

    if "— QUẢNG CÁO —" in content_text:
        content_text = content_text.replace(
            "— QUẢNG CÁO —", "")

    if DOWNLOAD_NOVEL_DEBUG and DEBUG_OBJ["extract_info_novel_sstruyen"]:
        print(Fore.BLUE + f'{"Title:":<20}' + Style.RESET_ALL + f'{title.text.strip(): >49}')
        print(Fore.GREEN + '<' + '='*68 + '<' + Style.RESET_ALL)

    return title.text.strip(), content_text.strip()

def add_chapter_to_docx(docx_obj: docx.Document, title: str, content: str):
    """
    Add a chapter to the docx object
    :param docx_obj: The docx object
    :param title: The title of the chapter
    :param content: The content of the chapter
    :return: The docx object
    """
    if DOWNLOAD_NOVEL_DEBUG:
        print(Fore.GREEN + '>' + '='*68 + '>' + Style.RESET_ALL)
        print(Fore.YELLOW + 'DownloadNovelController: add_chapter_to_docx'.center(70) + Style.RESET_ALL)
        print(Fore.BLUE + f'{"Title:":<20}' + Style.RESET_ALL + f'{title: >49}')
    
    p = docx_obj.add_heading(title, level=1)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p = docx_obj.add_paragraph(page_break)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p = docx_obj.add_paragraph(content.strip())
    docx_obj.add_page_break()
    
    return docx_obj

def download_novel(type_novel: int, start_chap: int, end_chap: int, link_id: str, title: str, author: str):
    """
    Download a novel
    :param type_novel: The type of the novel
    :param start_chap: The start chapter of the novel
    :param end_chap: The end chapter of the novel
    :param title: The title of the novel
    :param author: The author of the novel
    :return: None
    """
    try:
        
        if DOWNLOAD_NOVEL_DEBUG:
            print(Fore.GREEN + '>' + '='*68 + '>' + Style.RESET_ALL)
            print(Fore.YELLOW + 'DownloadNovelController: download_novel'.center(70) + Style.RESET_ALL)
            print(Fore.BLUE + f'{"Type novel:":<20}' + Style.RESET_ALL + f'{type_novel: >49}')
            print(Fore.BLUE + f'{"Start chapter:":<20}' + Style.RESET_ALL + f'{start_chap: >49}')
            print(Fore.BLUE + f'{"End chapter:":<20}' + Style.RESET_ALL + f'{end_chap: >49}')
            print(Fore.BLUE + f'{"Title:":<20}' + Style.RESET_ALL + f'{title: >49}')
            print(Fore.BLUE + f'{"Author:":<20}' + Style.RESET_ALL + f'{author: >49}')
        
        if type_novel == 1:
            link_chap = sstruyen_link
        else:
            link_chap = link_chap
        
        docx_obj = docx.Document()
        for i in range(start_chap, end_chap + 1):
            link_chap = link_chap.format(link_id, i)
            title, content = extract_info_novel_sstruyen(link_chap)
            docx_obj = add_chapter_to_docx(docx_obj, title, content)
            
        docx_obj.save(f"{title}.docx")
        
        core_properties = docx_obj.core_properties
        core_properties.author = author
        core_properties.comments = "Generated by Crawl Manga - An Đào"
        
        docx_obj.save(f"{title} chap {start_chap} - {end_chap}.docx")
    except Exception as e:
        if DOWNLOAD_NOVEL_DEBUG:
            print(Fore.RED + f'{"Error:":<20}' + Style.RESET_ALL + f'{e: >49}')
            print(Fore.GREEN + '<' + '='*68 + '<' + Style.RESET_ALL)
